name: app
services:
- name: ycphacks
  github:
    repo: YCPHacks/ycphacks
    branch: main
    deploy_on_push: true
  http_port: 3000
  source_dir: src
databases:
- name: db-mysql-nyc1-29905
  engine: MYSQL
  version: "8"
  production: true
  cluster_name: db-mysql-nyc1-29905
  db_name: defaultdb
  db_user: app_user
region: nyc
